version: "2"
services: 
  client:
    image: webapp-client
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - ./client:/client 
    links:
      - server 
    networks: 
      - webappnetwork
  server:
    image: webapp-server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./server:/server 
    depends_on: 
      - mongodb
    networks: 
      - webappnetwork
  mongodb:
    image: mongo 
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongodb --noauth --smallfiles
    networks: 
      - webappnetwork
networks: 
  webappnetwork:
    driver: bridge
